name: Update Commit Count Badge

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Count commits
        id: count
        run: |
          COMMIT_COUNT=$(git rev-list --count main)
          echo "count=$COMMIT_COUNT" >> $GITHUB_OUTPUT

      - name: Checkout badges repo
        uses: actions/checkout@v4
        with:
          repository: zoyern/badges
          token: ${{ secrets.GITHUB_TOKEN }}
          path: badges-repo

      - name: Generate badge
        run: |
          COMMIT_COUNT=${{ steps.count.outputs.count }}
          mkdir -p badges-repo
          cat > badges-repo/42_school_projects_commits.svg << EOF
          <svg xmlns="http://www.w3.org/2000/svg" width="140" height="28">
            <defs>
              <linearGradient id="grad" x1="0%" y1="0%" x2="0%" y2="100%">
                <stop offset="0%" style="stop-color:#555;stop-opacity:1" />
                <stop offset="100%" style="stop-color:#333;stop-opacity:1" />
              </linearGradient>
            </defs>
            <rect width="75" height="28" fill="url(#grad)" rx="4"/>
            <rect x="75" width="65" height="28" fill="#666" rx="4"/>
            <text x="37.5" y="18" fill="#fff" font-family="system-ui,-apple-system,sans-serif" font-size="11" text-anchor="middle" font-weight="500">commits</text>
            <text x="107.5" y="18" fill="#fff" font-family="system-ui,-apple-system,sans-serif" font-size="11" text-anchor="middle" font-weight="600">$COMMIT_COUNT</text>
          </svg>
          EOF

      - name: Commit badge to badges repo
        run: |
          cd badges-repo
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add 42_school_projects_commits.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update 42_school_projects commit count"
          git push