name: Update Commit Count Badge

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # Cette ligne est cruciale

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Ajoute aussi cette ligne

      - name: Count commits
        id: count
        run: |
          COMMIT_COUNT=$(git rev-list --count main)
          echo "count=$COMMIT_COUNT" >> $GITHUB_OUTPUT

      - name: Generate badge
        run: |
          COMMIT_COUNT=${{ steps.count.outputs.count }}
          mkdir -p .github/badges
          cat > .github/badges/commits.svg << EOF
          <svg xmlns="http://www.w3.org/2000/svg" width="120" height="28">
            <rect width="65" height="28" fill="#555"/>
            <rect x="65" width="55" height="28" fill="#4c1"/>
            <text x="32.5" y="18" fill="#fff" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="12" text-anchor="middle">commits</text>
            <text x="92.5" y="18" fill="#fff" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="12" text-anchor="middle" font-weight="bold">$COMMIT_COUNT</text>
          </svg>
          EOF

      - name: Commit badge
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/badges/commits.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update commit count badge [skip ci]"
          git push