name: Update Commit Count Badge
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Count commits
        id: count
        run: |
          COMMIT_COUNT=$(git rev-list --count main)
          echo "count=$COMMIT_COUNT" >> $GITHUB_OUTPUT
      - name: Checkout zoyern/zoyern repo
        uses: actions/checkout@v4
        with:
          repository: zoyern/zoyern
          token: ${{ secrets.BADGE_TOKEN }}
          path: zoyern-repo
      - name: Generate badge
        run: |
          COMMIT_COUNT=${{ steps.count.outputs.count }}
          mkdir -p zoyern-repo/assets/navigation
          cat > zoyern-repo/assets/navigation/42_school_commits.svg << EOF
          <svg xmlns="http://www.w3.org/2000/svg" width="150" height="30">
            <defs>
              <!-- Dégradé partie gauche -->
              <linearGradient id="gradLeft" x1="0%" y1="0%" x2="0%" y2="100%">
                <stop offset="0%" style="stop-color:#666;stop-opacity:1" />
                <stop offset="100%" style="stop-color:#444;stop-opacity:1" />
              </linearGradient>

              <!-- Dégradé partie droite -->
              <linearGradient id="gradRight" x1="0%" y1="0%" x2="0%" y2="100%">
                <stop offset="0%" style="stop-color:#888;stop-opacity:1" />
                <stop offset="100%" style="stop-color:#555;stop-opacity:1" />
              </linearGradient>

              <!-- Ombre pour texte -->
              <filter id="textShadow" x="-20%" y="-20%" width="140%" height="140%">
                <feDropShadow dx="0" dy="1" stdDeviation="0.3" flood-color="#000" flood-opacity="0.25"/>
              </filter>
            </defs>

            <!-- Bordure arrondie -->
            <rect x="0" y="0" width="150" height="30" rx="5" ry="5" fill="none" stroke="#444" stroke-width="0.6"/>

            <!-- Parties du badge -->
            <polygon points="0,0 90,0 98,30 0,30" fill="url(#gradLeft)" />
            <polygon points="90,0 150,0 150,30 98,30" fill="url(#gradRight)" />

            <!-- Texte gauche -->
            <text x="45" y="19" fill="#fff" font-family="Montserrat,system-ui,sans-serif" font-size="10" text-anchor="middle" font-weight="600" text-transform="uppercase" filter="url(#textShadow)">
              42 SCHOOL
            </text>

            <!-- Texte droite avec flèche unique collée -->
            <text x="124" y="19" font-family="Montserrat,system-ui,sans-serif" font-size="10" text-anchor="middle" font-weight="600" fill="#fff" text-transform="uppercase" filter="url(#textShadow)">
              $COMMIT_COUNT<tspan dx="2" fill="#4caf50" font-weight="600">⇵</tspan>
            </text>
          </svg>
          EOF




      - name: Commit badge to zoyern/zoyern repo
        run: |
          cd zoyern-repo
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add assets/navigation/42_school_commits.svg
          git diff --quiet && git diff --staged --quiet || git commit -m "Update 42_school: ${{ steps.count.outputs.count }} commits"
          git push
